export const teamMembersEs = [
  {
    name: "Armando Flores",
    role: "Team Leader",
    bio: "Especialista en derecho migratorio con más de 15 años de experiencia. Team Leader que coordina operaciones y forma equipos de alto desempeño en asesoría migratoria corporativa.",
    img: "armando-flores",
  },
  {
    name: "Sofía Kargl",
    role: "Procesos Migratorios",
    bio: "Profesional en procesos migratorios con enfoque en eficiencia y trato cercano. Acompaña a cada cliente con organización y atención personalizada en todas las etapas.",
    img: "sofia-kargl",
  },
  {
    name: "Aylin Patiño",
    role: "Abogada Migratoria",
    bio: "Abogada especializada en migración con más de cinco años de experiencia. Atiende a extranjeros y sus familias con cercanía y acompañamiento personalizado. Ofrece atención en árabe.",
    img: "aylin-patino",
  },
  {
    name: "Pedro Márquez",
    role: "Comunidad China",
    bio: "Especialista en procesos migratorios para la comunidad china en México. Facilita cada trámite con conocimiento cultural y atención en mandarín, conectando culturas en cada proceso.",
    img: "pedro-marquez",
  },
  {
    name: "Stephany Torres",
    role: "Movilidad Global",
    bio: "Especialista en movilidad global para empresas multinacionales. Su experiencia previa en el Instituto Nacional de Migración aporta certeza técnica a cada proceso, con atención cercana y personalizada al cliente.",
    img: "stephany-torres",
  },
  {
    name: "Ivonne Morales",
    role: "Derecho Migratorio Corporativo",
    bio: "Especialista en derecho migratorio corporativo para la contratación de talento extranjero. Con experiencia en derecho de los refugiados y protección del asilo, aporta una perspectiva única en movilidad humana e inclusión.",
    img: "ivonne-morales",
  },
  {
    name: "Mario Rivera",
    role: "Team Leader",
    bio: "Abogado especialista en materia migratoria con más de 15 años de experiencia. Team Leader responsable de coordinar y supervisar la ejecución de procesos migratorios corporativos.",
    img: "mario-rivera",
  },
  {
    name: "Lesly Sánchez",
    role: "Documentación Migratoria",
    bio: "Abogada especialista en procesos migratorios y documentación, con más de dos años de experiencia. Se distingue por el seguimiento puntual de cada trámite y la atención cercana al cliente.",
    img: "lesly-sanchez",
  },
  {
    name: "Ethel Despy",
    role: "Atención al Cliente",
    bio: "Asociada en el equipo de atención al cliente. Acompaña cada proceso migratorio con proactividad, atención al detalle y disponibilidad constante. Ofrece atención personalizada en francés.",
    img: "ethel-despy",
  },
  {
    name: "Ricardo Ángeles",
    role: "Movilidad Global",
    bio: "Especialista en movilidad global con ocho años de experiencia. Ejecuta procesos migratorios con agilidad y trato cercano, asegurando una experiencia fluida para el cliente. Atención bilingüe español-inglés.",
    img: "ricardo-angeles",
  },
  {
    name: "Dalia Duarte",
    role: "Abogada Migratoria",
    bio: "Abogada con tres años de experiencia en materia migratoria. Especializada en acompañamiento a personas y familias en procesos de movilidad internacional.",
    img: "dalia-duarte",
  },
  {
    name: "Alexia Del Jobo",
    role: "Procesos Migratorios",
    bio: "Asociada en procesos migratorios con experiencia previa en el Instituto Nacional de Migración. Defensora de la movilidad digna y segura, acompaña cada proceso con empatía y respeto por los derechos de cada persona.",
    img: "alexia-del-jobo",
  },
  {
    name: "María José Ramírez",
    role: "Movilidad Global",
    bio: "Especialista en movilidad global, reconocida por su pensamiento estratégico, responsabilidad y atención al detalle. Aporta claridad y precisión en cada caso. Atiende en español, inglés, francés y portugués.",
    img: "maria-jose-ramirez",
  },
  {
    name: "Abigail De Arcos",
    role: "Trámites y Documentación",
    bio: "Profesional en trámites y documentación migratoria. Atiende múltiples procesos con eficiencia, orden y enfoque resolutivo, aportando claridad y valor en cada caso.",
    img: "abigail-de-arcos",
  },
  {
    name: "Teresa Galicia",
    role: "Team Leader Outbound",
    bio: "Team Leader del área Outbound. Lidera estrategias migratorias para visas de corta y larga estancia con alcance en América y Asia. Se distingue por su cercanía con el cliente y capacidad de simplificar procesos complejos.",
    img: "teresa-galicia",
  },
  {
    name: "Jesús Olvera",
    role: "Visados Internacionales",
    bio: "Especialista en visados de corto y mediano plazo para Estados Unidos, Asia, Europa y África. Destaca por su asesoría clara y eficiente, orientada a facilitar procesos migratorios exitosos.",
    img: "jesus-olvera",
  },
  {
    name: "Margarita Hernández",
    role: "Team Leader GDS",
    bio: "Team Leader en Global Delivery Services (GDS) con más de veinte años de experiencia en materia migratoria. Especialista en análisis documental, cumplimiento normativo y supervisión de procesos de principio a fin.",
    img: "margarita-hernandez",
  },
  {
    name: "Yael Escalona",
    role: "Global Delivery Services",
    bio: "Profesional de Global Delivery Services (GDS) con ocho años de experiencia migratoria. Especializada en control de procesos, eficiencia operativa y seguimiento oportuno de procedimientos ante autoridades.",
    img: "yael-escalona",
  },
  {
    name: "Alejandra López",
    role: "Global Delivery Services",
    bio: "Profesional de Global Delivery Services (GDS) con cuatro años de experiencia migratoria. Conocimiento sólido del marco legal, con enfoque en la resolución eficiente de procesos migratorios y atención a clientes, aportando valor estratégico a su área.",
    img: "alejandra-lopez",
  },
  {
    name: "Andrea Jiménez",
    role: "Lead Monterrey",
    bio: "Profesional de Global Delivery Services (GDS) y Lead en la oficina de Monterrey. Responsable de que cada trámite se ejecute con precisión ante el INM. Aporta orden y confianza a cada proceso.",
    img: "andrea-jimenez",
  },
  {
    name: "Joaquín Arjona",
    role: "Derecho Migratorio",
    bio: "Abogado con más de 18 años de experiencia en derecho migratorio. Referente en la materia con trayectoria como catedrático en diplomados especializados y autor de publicaciones sobre migración.",
    img: "joaquin-arjona",
  },
  {
    name: "Jorge Cedillo",
    role: "Trámites Migratorios",
    bio: "Especialista en trámites migratorios con más de 20 años de experiencia. Coordina y ejecuta procedimientos a nivel nacional con precisión y conocimiento normativo.",
    img: "jorge-cedillo",
  },
  {
    name: "Miguel Godínez",
    role: "Operaciones",
    bio: "Integrante del equipo de Operaciones con presencia en las oficinas de Cancún, Monterrey y Ciudad de México. Más de tres años de experiencia asegurando procesos migratorios ágiles y personalizados.",
    img: "miguel-godinez",
  },
  {
    name: "Iván Jiménez",
    role: "Operations Associate",
    bio: "Operations Associate con experiencia migratoria. Ejecuta trámites en sitio ante autoridades, asegurando cumplimiento normativo y resolución ágil en cada proceso.",
    img: "ivan-jimenez",
  },
  {
    name: "Armando Manuel Saavedra",
    role: "Procesos Migratorios",
    bio: "Profesional en el ámbito migratorio con 12 años de experiencia. Reconocido por su atención personalizada de alta calidad y un servicio profesional en cada trámite.",
    img: "armando-manuel-saavedra",
  },
  {
    name: "María Fernanda Rico",
    role: "Trámites Migratorios",
    bio: "Profesional en trámites migratorios con experiencia en atención a clientes y representación ante autoridades. Acompaña cada proceso con claridad y trato cercano.",
    img: "maria-fernanda-rico",
  },
  {
    name: "Jaime Segura",
    role: "Procesos en Campo",
    bio: "Responsable de la ejecución de procesos migratorios en campo. Aporta orden, agilidad y cumplimiento, asegurando una experiencia eficiente y respuesta oportuna a cada cliente.",
    img: "jaime-segura",
  },
  {
    name: "Minerva Sierra",
    role: "Operaciones Monterrey",
    bio: "Associate de Operaciones en la oficina de Monterrey. Responsable de la preparación y presentación de trámites ante autoridades, con acompañamiento directo al cliente y atención personalizada.",
    img: "minerva-sierra",
  },
  {
    name: "Gustavo Pérez",
    role: "Logística Documental",
    bio: "Responsable de logística documental. Asegura la entrega oportuna de documentación en cada proceso, con eficiencia y cumplimiento en cada servicio.",
    img: "gustavo-perez",
  },
  {
    name: "Gabriela Valladolid",
    role: "Administración y Finanzas",
    bio: "Gerente de Administración y Finanzas con más de 14 años de experiencia. Se distingue por su precisión, ética profesional y orientación a resultados.",
    img: "gabriela-valladolid",
  },
  {
    name: "Diana Guzmán",
    role: "Finanzas",
    bio: "Responsable del área financiera. Aporta control, análisis y optimización de recursos para respaldar la operación y las decisiones estratégicas de la firma.",
    img: "diana-guzman",
  },
  {
    name: "María Eugenia Flores",
    role: "Office Manager",
    bio: "Office Manager responsable de la coordinación administrativa y apoyo en recursos humanos. Soporte directo a la Dirección General para la operación diaria de la firma.",
    img: "maria-eugenia-flores",
  },
] as const;

export const teamMembersEn = teamMembersEs.map((member) => ({ ...member }));
export const teamMembersZh = teamMembersEs.map((member) => ({ ...member }));
